page_url = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/requestPasswordResetCode'
username_input = '//input[@name="username"]'
cancel_button = '//button[text()=" Cancel "]'
reset_password_button = '//button[text()=" Reset Password "]'
error_message = '//span[text()="Required"]'
